export const copy = {
  campaignTwo: {
    question: "어떤 상품을 홍보할까요?",
    description: "브랜드에서 추출한 상품 중 하나를 선택해 주세요.",
    productList: "대표 상품 선택",
    missingTitle: "선택할 상품이 없어요",
    missingDescription: "브랜드 탭에서 상품 추출 결과를 확인해 주세요.",
    brandLink: "브랜드 확인하기",
    generate: "이 상품으로 캠페인 만들기",
    submitting: "캠페인을 시작하고 있어요",
    selected: "선택됨",
    generating: "선택한 상품으로 이미지를 만들고 있어요.",
    complete: "캠페인 이미지가 완성됐어요.",
    failed: "일부 이미지를 만들지 못했어요.",
    retry: "선택한 상품으로 다시 만들기",
    progress: (done: number, total: number) => `${total}장 중 ${done}장 완료`,
    position: (day: number, format: string) =>
      `D${day} · ${format === "story" ? "스토리" : format === "carousel" ? "캐러셀" : "피드"}`,
    imageAlt: (name: string) => `${name} 캠페인 이미지`,
    imageMissing: "상품 이미지 없음",
  },
  dashboard: {
    headline: "우리 브랜드의",
    headlineSecond: "다음 캠페인",
    recentTasks: "최근 끝낸 작업",
    summary: "브랜드와 캠페인 요약",
    myBrand: "내 브랜드",
    brandSettings: "브랜드 정보 보기",
    progress: "캠페인 진행 현황",
    completed: "완료한 캠페인",
    emptyRecentTasks: "아직 끝낸 작업이 없어요.",
    emptyCompleted: "아직 완료한 캠페인이 없어요.",
  },
  brandCompletion: {
    save: "저장",
    cancel: "취소",
    edit: (title: string) => `${title} 입력`,
    removeKeyword: (keyword: string) => `${keyword} 삭제`,
    invalid: "입력 내용을 확인해주세요.",
    titles: {
      name: "브랜드 이름은 무엇인가요?",
      address: "브랜드의 주소를 알려주세요",
      industry: "어떤 업종인가요?",
      tagline: "브랜드를 한 줄로 소개해주세요",
      logo_url: "브랜드 로고가 있나요?",
      palette: "브랜드 색상을 알려주세요",
      mood_keywords: "어떤 분위기로 보여주고 싶나요?",
      font_feel: "어떤 글씨 느낌이 어울리나요?",
      voice: "고객에게 어떤 말투로 이야기할까요?",
      target_audience: "주로 어떤 고객을 위한 브랜드인가요?",
      products: "제품·서비스를 알려주세요",
    },
    price: (name: string) => `${name}의 가격을 알려주세요`,
    suggestions: {
      tagline: (name: string) => [
        `${name}와 함께하는 일상`,
        `나에게 맞는 선택, ${name}`,
        `${name}에서 만나는 새로운 경험`,
      ],
      mood_keywords: [
        "따뜻한, 편안한, 자연스러운",
        "단정한, 차분한, 신뢰감 있는",
        "밝은, 활기찬, 친근한",
      ],
      font_feel: ["단정하고 읽기 쉬운 고딕", "차분하고 섬세한 명조", "부드럽고 친근한 둥근 글씨"],
      voice: ["친근하고 편안한 말투", "간결하고 명확한 말투", "차분하고 정중한 말투"],
      target_audience: [
        "이 분야를 처음 접하는 고객",
        "일상에서 편리하게 이용하려는 고객",
        "자신의 취향에 맞는 선택을 원하는 고객",
      ],
    },
  },
  app: {
    name: "Margo",
    description:
      "사이트 URL을 넣으면 브랜드를 읽고, 방향을 고르면 브랜드 에셋 / 인스타 홍보물 / AI 영상을 만든다.",
  },
  nav: {
    brands: "브랜드",
    campaigns: "캠페인",
  },
  sidebar: {
    name: "Margo",
    logo: "Margo 로고",
    label: "Margo 사이드바",
    workspace: "Margo 작업 공간",
    dashboard: "대시보드",
    newCampaign: "새 캠페인 만들기",
    newCampaignLabel: "사이드바에서 새 캠페인 만들기",
    navigation: "주요 메뉴",
    collapse: "사이드바 접기",
    expand: "사이드바 펼치기",
    plan: "Free",
    usage: "사용량",
    usageDescription: "이 계정에서 사용한 브랜드 분석과 AI 토큰입니다.",
    usageBrands: "브랜드 분석",
    usageInputTokens: "입력 토큰",
    usageOutputTokens: "출력 토큰",
    usageTimes: (count: number) => `${count}회`,
    usageTokens: (count: number) => count.toLocaleString("ko-KR"),
    usageLoadFailed: "사용량을 불러오지 못했어요.",
    pending: "준비 중",
    support: "도움말",
    account: "계정 설정",
    signOut: "로그아웃",
    openMenu: "메뉴 열기",
  },
  login: {
    title: "로그인",
    description: "이메일과 비밀번호로 로그인해 주세요.",
    email: "이메일",
    emailPlaceholder: "you@example.com",
    password: "비밀번호",
    submit: "로그인",
    submitting: "로그인 중",
    signUpPrompt: "계정이 없으면",
    invalidInput: "이메일 형식이 올바르지 않아요.",
    required: "로그인해 주세요.",
  },
  signUp: {
    title: "회원가입",
    description: "이메일과 비밀번호로 계정을 만들어 주세요.",
    name: "이름",
    namePlaceholder: "홍길동",
    passwordHint: "8자 이상",
    passwordConfirm: "비밀번호 확인",
    consent: "만 14세 이상이며, 이용약관과 개인정보 수집·이용에 동의합니다. (필수)",
    submit: "회원가입",
    submitting: "가입 중",
    loginPrompt: "이미 계정이 있으면",
    nameRequired: "이름을 입력해 주세요.",
    nameTooLong: "이름은 50자 이내로 입력해 주세요.",
    nameInvalid: "이름에 쓸 수 없는 문자가 있어요.",
    invalidEmail: "이메일 형식이 올바르지 않아요.",
    passwordTooShort: "비밀번호를 8자 이상으로 입력해 주세요.",
    passwordTooLong: "비밀번호는 72자 이내로 입력해 주세요.",
    passwordMismatch: "비밀번호가 서로 달라요.",
    consentRequired: "필수 동의 항목에 동의해 주세요.",
    confirmSent: "가입 확인 메일을 보냈어요. 메일에서 확인한 뒤 로그인해 주세요.",
  },
  home: {
    headline: "무엇을 홍보해드릴까요?",
    greeting: (name: string) => `${name}님, 무엇을 홍보해드릴까요?`,
    urlPlaceholder: "사이트 URL을 붙여 넣으세요",
    urlHint: "예: https://example.com",
    submit: "분석 시작",
  },
  brands: {
    title: "브랜드",
    emptyTitle: "아직 분석한 브랜드가 없다",
    emptyDescription: "홈에서 사이트 URL을 넣으면 여기에 쌓인다.",
  },
  brandAnalysis: {
    saveFailed: "브랜드 정보를 저장하지 못했어요. 다시 시도해 주세요.",
    loadFailed: "저장한 브랜드 정보를 불러오지 못했어요.",
    title: "브랜드 분석 완료",
    description: "웹사이트를 분석하여 브랜드 정보를 추출했어요.",
    loadingTitle: "브랜드 정보를 분석하고 있어요",
    loadingDescription: "사이트의 로고, 색상, 분위기와 제품을 확인하고 있어요.",
    progress: "분석 진행률",
    percent: (value: number) => `${value}%`,
    invalidUrl: "유효한 HTTP(S) 사이트 URL을 입력해라.",
    unexpected: "사이트 분석 중 예상하지 못한 오류가 발생했다.",
    homepageFailed: "사이트의 첫 페이지를 읽지 못했다.",
    collectRateLimited: "사이트 수집이 잠시 제한됐다. 잠시 후 다시 시도해 주세요.",
    collectCreditsExhausted: "사이트 수집 크레딧이 소진됐다.",
    collectAuthFailed: "사이트 수집 API 인증에 실패했다.",
    collectTimeout: "사이트 수집 시간이 초과됐다.",
    collectUnavailable: "사이트를 수집하지 못했다.",
    aiRateLimited: "AI 요청이 잠시 제한됐다. 잠시 후 다시 시도해 주세요.",
    selectCampaign: "캠페인 선택",
    basicInfo: "기본 정보",
    palette: "브랜드 색상",
    mood: "브랜드 분위기",
    fontFeel: "글꼴 느낌",
    voice: "말투",
    moodKeywords: "분위기 키워드",
    targetAudience: "주요 고객",
    products: "제품·서비스 전체",
    productCount: (count: number) => `${count}개`,
    unavailable: "확인되지 않음",
    nameMissing: "브랜드명을 찾지 못했어요.",
    logoMissing: "로고를 찾지 못했어요.",
    industryMissing: "업종을 찾지 못했어요.",
    taglineMissing: "소개 문구를 찾지 못했어요.",
    paletteMissing: "브랜드 색상을 찾지 못했어요.",
    fontFeelMissing: "글꼴 느낌을 찾지 못했어요.",
    voiceMissing: "말투를 찾지 못했어요.",
    moodKeywordsMissing: "분위기 키워드를 찾지 못했어요.",
    audienceMissing: "주요 고객을 찾지 못했어요.",
    productsMissing: "제품·서비스를 찾지 못했어요.",
    logoAlt: (name: string) => `${name} 로고`,
    productImageAlt: (name: string) => `${name} 이미지`,
    colorLabel: (color: string) => `브랜드 색상 ${color}`,
  },
  campaigns: {
    title: "캠페인",
    galleryTitle: "최근 캠페인",
    newCampaign: "새 캠페인 만들기",
    statuses: {
      processing: "진행 중",
      done: "완료",
      draft: "초안",
    },
    statusNavigation: "캠페인 상태",
    statusEmptyTitle: "이 상태의 캠페인이 없어요",
    statusEmptyDescription: "다른 상태를 선택해 확인해 주세요.",
    heading: "어떤 캠페인을 시작할까요?",
    description: "브랜드에 맞는 캠페인을 선택해 주세요.",
    selectionLabel: "캠페인 선택",
    catalogEmpty: "아직 등록된 캠페인이 없어요",
    select: (name: string) => `${name} 선택`,
    preview: (name: string) => `${name} 상세 보기`,
    imageAlt: (name: string) => `${name} 미리보기`,
    selectAction: "선택하기",
    close: "상세 창 닫기",
    goal: "목표",
    duration: "기간",
    channels: "채널",
    schedule: "게시 일정",
    day: (day: number) => `${day}일차`,
    days: (days: number) => `${days}일`,
    outputs: "생성할 산출물",
    outputsPending: "게시물별 이미지·영상 수량과 비율은 아직 정해지지 않았어요.",
    scope: "일정표와 게시물 소재를 만들어요. 자동 게시는 추후 연결돼요.",
    backToSelection: "캠페인 다시 선택",
    selectedCampaign: "선택한 캠페인",
  },
  assets: {
    title: "결과물",
    emptyTitle: "아직 결과물이 없다",
    emptyDescription: "캠페인을 실행하면 브랜드 에셋, 피드, 영상이 여기에 쌓인다.",
  },
  common: {
    dismissError: "오류 알림 닫기",
    retry: "다시 시도",
  },
} as const;
