import type { CampaignPreview } from "@/lib/types";

// docs/PLAN.md의 초기 카탈로그. 일정은 캠페인별 정의가 연결되면 제공한다.
export const campaigns: CampaignPreview[] = [
  {
    key: "signature_grid",
    name: "시그니처 그리드",
    goal: "프로필 그리드 9장을 한 세트로 만들어 브랜드가 한눈에 읽히게 한다",
    duration_days: 9,
    channels: ["Instagram 피드"],
    image: null,
    schedule: [],
  },
  {
    key: "one_product_three_scenes",
    name: "한 상품, 세 장면",
    goal: "대표 상품 하나를 세 가지 사용 장면으로 보여 줘 구매 후 모습을 상상하게 한다",
    duration_days: 5,
    channels: ["Instagram 피드", "캐러셀", "스토리"],
    image: null,
    schedule: [
      { day: 1, channel: "Instagram", format: "Feed", purpose: "대표 상품 소개" },
      { day: 2, channel: "Instagram", format: "Feed · Story", purpose: "첫 번째 사용 장면" },
      { day: 3, channel: "Instagram", format: "Feed · Story", purpose: "두 번째 사용 장면" },
      { day: 4, channel: "Instagram", format: "Feed · Story", purpose: "세 번째 사용 장면" },
      { day: 5, channel: "Instagram", format: "Carousel", purpose: "세 장면 정리" },
    ],
  },
  {
    key: "objection_clear",
    name: "망설임 제거",
    goal: "가격·배송·환불·비교 반론에 하루 하나씩 답한다",
    duration_days: 6,
    channels: ["Instagram 캐러셀", "스토리"],
    image: null,
    schedule: [],
  },
  {
    key: "countdown_launch",
    name: "카운트다운 런칭",
    goal: "출시일 앞뒤 7일. 티저에서 사용법까지",
    duration_days: 7,
    channels: ["Instagram", "LinkedIn"],
    image: null,
    schedule: [],
  },
  {
    key: "limited_offer",
    name: "기간 한정 오퍼",
    goal: "혜택과 마감을 5일 반복하고 광고로 도달을 확보한다",
    duration_days: 5,
    channels: ["Instagram", "Meta 광고"],
    image: null,
    schedule: [],
  },
  {
    key: "maker_series",
    name: "만든 사람 시리즈",
    goal: "만든 사람의 이야기를 8편의 글로 쓴다",
    duration_days: 28,
    channels: ["Threads", "LinkedIn"],
    image: null,
    schedule: [],
  },
  {
    key: "use_cases",
    name: "사용 장면",
    goal: "누가 언제 어디서 쓰는지 하루 한 장면",
    duration_days: 7,
    channels: ["Instagram 피드", "스토리"],
    image: null,
    schedule: [],
  },
  {
    key: "old_way_vs_us",
    name: "기존 방식 vs 우리",
    goal: "시간·비용·결과 축으로 기존 방식과 비교한다",
    duration_days: 5,
    channels: ["Instagram 캐러셀", "LinkedIn"],
    image: null,
    schedule: [],
  },
  {
    key: "one_product_a_day",
    name: "상품 하나씩",
    goal: "같은 템플릿으로 하루 상품 하나, 가격 포함",
    duration_days: 10,
    channels: ["Instagram 피드", "Pinterest"],
    image: null,
    schedule: [],
  },
  {
    key: "seasonal",
    name: "시즌 기획",
    goal: "시즌 D-day를 역산해 살 이유를 만든다",
    duration_days: 10,
    channels: ["Instagram", "Meta 광고"],
    image: null,
    schedule: [],
  },
  {
    key: "proof_numbers",
    name: "숫자로 증명",
    goal: "사이트에 공개된 숫자·사실을 하루 하나 보여 준다",
    duration_days: 5,
    channels: ["Instagram 피드", "LinkedIn"],
    image: null,
    schedule: [],
  },
  {
    key: "field_knowledge",
    name: "분야 지식 시리즈",
    goal: "저장할 만한 팁 캐러셀. 마지막 장만 브랜드",
    duration_days: 14,
    channels: ["Instagram 캐러셀", "Threads", "Pinterest"],
    image: null,
    schedule: [],
  },
  {
    key: "waitlist",
    name: "사전 등록",
    goal: "출시 전 문제 공감에서 등록 링크까지 7일",
    duration_days: 7,
    channels: ["Threads", "LinkedIn", "Instagram 스토리"],
    image: null,
    schedule: [],
  },
  {
    key: "hook_test",
    name: "후크 테스트",
    goal: "같은 상품에 후크 4개를 광고로 동시에 돌려 반응을 비교한다",
    duration_days: 5,
    channels: ["Meta 광고"],
    image: null,
    schedule: [],
  },
  {
    key: "one_line_empathy",
    name: "공감 한 줄",
    goal: "제품 언급 없는 한 줄 공감 글. 마지막 날만 링크",
    duration_days: 7,
    channels: ["Threads", "X"],
    image: null,
    schedule: [],
  },
];
